version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./es-volume:/usr/share/elasticsearch/data
      #- es-volume:/usr/share/elasticsearch/data
    ports:
      - 9200
      - 9300
    environment:
      #node.name: elasticsearch
      MAX_LOCKED_MEMORY: unlimited
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
    #  - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    #  - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/logs:/usr/share/logstash/logs
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  # filebeats:
  #   build:
  #     context: filebeats/
  #   command: filebeat -e -strict.perms=false
  #   volumes:
  #     - ./filebeats/config/logstash.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - ./filebeats/logs:/usr/share/filebeat/logs
  #   ports:
  #     - "5044:5044"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  es-hq:
    image: "elastichq/elasticsearch-hq"
    ports:
      - "5001:5000"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
#volumes:
#  es-volume:
